// --- Imports ---
import { Conference, Region, LocationType, FundingType } from './types';

// --- Conference Data ---
// This list contains the initial set of conferences and grant opportunities.
export const CONFERENCES: Conference[] = [
  {
    id: '2',
    name: 'AWS re:Invent 2026',
    description: 'The biggest cloud computing event of the year.',
    location: 'Las Vegas, NV',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Cloud',
    startDate: '2026-11-30',
    endDate: '2026-12-04',
    grantDeadline: '2026-09-15',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
      stipend: true,
    },
    applicationUrl: 'https://reinvent.awsevents.com/',
    tags: ['Cloud', 'AWS', 'Serverless'],
    imageUrl: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '3',
    name: 'Grace Hopper Celebration 2026',
    description: 'The world\'s largest gathering of women and non-binary technologists.',
    location: 'Anaheim, CA',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Diversity',
    startDate: '2026-10-27',
    endDate: '2026-10-30',
    grantDeadline: '2026-06-30',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://ghc.anitab.org/',
    tags: ['Diversity', 'Women in Tech'],
    imageUrl: 'https://images.unsplash.com/photo-1540575861501-7cf05a4b125a?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '5',
    name: 'PyCon Africa 2026',
    description: 'The annual gathering of the Python community in Africa.',
    location: 'Nairobi, Kenya',
    region: Region.AFRICA,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.PARTIAL,
    field: 'Python',
    startDate: '2026-09-22',
    endDate: '2026-09-26',
    grantDeadline: '2026-07-01',
    grantCoverage: {
      flight: false,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://africa.pycon.org/',
    tags: ['Python', 'Community'],
    imageUrl: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '6',
    name: 'Devcon 2026',
    description: 'The conference for Ethereum developers, researchers, and enthusiasts.',
    location: 'Mumbai, India',
    region: Region.ASIA,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.FULL,
    field: 'Blockchain',
    startDate: '2026-11-10',
    endDate: '2026-11-13',
    grantDeadline: '2026-08-30',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://devcon.org/',
    tags: ['Blockchain', 'Ethereum'],
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?auto=format&fit=crop&q=80&w=800',
    isComingSoon: true,
    isVerified: true,
  },
  {
    id: '9',
    name: 'EuroPython 2026',
    description: 'The largest community-run Python conference in Europe.',
    location: 'Kraków, Poland',
    region: Region.EUROPE,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.PARTIAL,
    field: 'Python',
    startDate: '2026-07-13',
    endDate: '2026-07-19',
    grantDeadline: '2026-05-15',
    grantCoverage: {
      flight: false,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://ep2026.europython.eu/',
    tags: ['Python', 'Data Science', 'Web'],
    imageUrl: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '11',
    name: 'Black Hat USA 2026',
    description: 'The world\'s leading information security event.',
    location: 'Las Vegas, NV',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Security',
    startDate: '2026-08-01',
    endDate: '2026-08-06',
    grantDeadline: '2026-05-15',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://www.blackhat.com/us-26/',
    tags: ['Security', 'Cybersecurity', 'Hacking'],
    imageUrl: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '12',
    name: 'WWDC 2026',
    description: 'Apple\'s Worldwide Developers Conference. Historically provides scholarships via the Swift Student Challenge.',
    location: 'Cupertino, CA',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Mobile',
    startDate: '2026-06-08',
    endDate: '2026-06-12',
    grantDeadline: '2026-04-10',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://developer.apple.com/wwdc/',
    tags: ['iOS', 'Swift', 'Apple'],
    imageUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '14',
    name: 'GopherCon 2026',
    description: 'The premier conference for Go developers. Offers a robust scholarship program for underrepresented groups.',
    location: 'Seattle, WA',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Go',
    startDate: '2026-08-03',
    endDate: '2026-08-06',
    grantDeadline: '2026-05-15',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://www.gophercon.com/',
    tags: ['Go', 'Backend', 'Cloud Native'],
    imageUrl: 'https://images.unsplash.com/photo-1516259762381-22954d7d3ad2?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '17',
    name: 'USENIX Security \'26',
    description: 'The 35th USENIX Security Symposium. Renowned for its extensive student travel grant program.',
    location: 'Vancouver, BC',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.FULL,
    field: 'Security',
    startDate: '2026-08-12',
    endDate: '2026-08-14',
    grantDeadline: '2026-06-01',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://www.usenix.org/conference/usenixsecurity26',
    tags: ['Security', 'Research', 'Privacy'],
    imageUrl: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc51?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '18',
    name: 'SANS CyberTalent 2026',
    description: 'Focused on bridging the cybersecurity skills gap through dedicated scholarship academies.',
    location: 'Various / Virtual',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.FULL,
    field: 'Security',
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    grantDeadline: '2026-06-16',
    grantCoverage: {
      flight: false,
      hotel: false,
      ticket: true,
      stipend: true,
    },
    applicationUrl: 'https://www.sans.org/cybertalent/',
    tags: ['Security', 'Training', 'Scholarship'],
    imageUrl: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '15',
    name: 'RustConf 2026',
    description: 'The official conference for the Rust programming language.',
    location: 'Montreal, Canada',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.GLOBAL,
    fundingType: FundingType.FULL,
    field: 'Rust',
    startDate: '2026-09-08',
    endDate: '2026-09-11',
    grantDeadline: '2026-06-15',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://rustconf.com/',
    tags: ['Rust', 'Systems', 'WebAssembly'],
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '20',
    name: 'PASS Data Community Summit 2026',
    description: 'The premier conference for data professionals. Offers a scholarship program for first-time attendees and underrepresented groups.',
    location: 'Seattle, WA',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'DBA',
    startDate: '2026-11-09',
    endDate: '2026-11-11',
    grantDeadline: '2026-08-01',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://passdatacommunitysummit.com/',
    tags: ['SQL Server', 'Data', 'DBA', 'Cloud'],
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bbbda536339a?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '21',
    name: 'AfroTech 2026',
    description: 'The largest tech conference for Black professionals. Offers various scholarship and grant opportunities.',
    location: 'Houston, TX',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Diversity',
    startDate: '2026-11-02',
    endDate: '2026-11-06',
    grantDeadline: '2026-08-15',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://afrotech.com/',
    tags: ['Diversity', 'Black in Tech', 'Networking'],
    imageUrl: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '22',
    name: 'Lesbians Who Tech & Allies Summit 2026',
    description: 'The largest LGBTQ+ technology community in the world. Provides scholarships for underrepresented technologists.',
    location: 'New York, NY',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Diversity',
    startDate: '2026-10-05',
    endDate: '2026-10-07',
    grantDeadline: '2026-07-01',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
    },
    applicationUrl: 'https://lesbianswhotech.org/',
    tags: ['Diversity', 'LGBTQ+', 'Women in Tech'],
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  },
  {
    id: '23',
    name: 'Tapia Conference 2026',
    description: 'The Richard Tapia Celebration of Diversity in Computing Conference. Offers extensive travel grants for students.',
    location: 'Atlanta, GA',
    region: Region.NORTH_AMERICA,
    locationType: LocationType.USA,
    fundingType: FundingType.FULL,
    field: 'Diversity',
    startDate: '2026-09-16',
    endDate: '2026-09-18',
    grantDeadline: '2026-04-30',
    grantCoverage: {
      flight: true,
      hotel: true,
      ticket: true,
      stipend: true,
    },
    applicationUrl: 'https://tapiaconference.cmd-it.org/',
    tags: ['Diversity', 'Computing', 'Student Grant'],
    imageUrl: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?auto=format&fit=crop&q=80&w=800',
    isVerified: true,
  }
];

// --- Success Stories ---
// Testimonials from users who have successfully received grants.
export const SUCCESS_STORIES = [
  {
    id: 'user-story',
    userName: 'Gloria Obono',
    userRole: 'Software Engineer',
    conferenceName: 'AWS re:Invent 2024',
    story: 'In 2024, right after my graduation, I won the AWS re:Invent grant. It was an experience that changed my life forever, opening doors to the global tech community.',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '1',
    userName: 'Amina Chen',
    userRole: 'CS Student',
    conferenceName: 'GTC 2024',
    story: 'The NVIDIA GTC travel grant allowed me to meet my current mentor and see AI research in action. It changed my career trajectory!',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '2',
    userName: 'Marcus Johnson',
    userRole: 'Junior Developer',
    conferenceName: 'AWS re:Invent 2024',
    story: 'The "All In" scholarship covered my entire trip to Vegas. I got my AWS certification and landed a Cloud Engineer role shortly after.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '3',
    userName: 'Elena Rodriguez',
    userRole: 'Security Researcher',
    conferenceName: 'USENIX Security \'24',
    story: 'Thanks to the student travel grant, I was able to present my first paper in Vancouver. The networking opportunities were invaluable.',
    avatarUrl: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&q=80&w=800',
  },
  {
    id: '4',
    userName: 'Sarah Jenkins',
    userRole: 'Cybersecurity Analyst',
    conferenceName: 'SANS CyberTalent',
    story: 'The SANS scholarship academy provided me with the training and GIAC certifications I needed to pivot into security from a non-tech background.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=800',
  }
];
